version: '3.7'
services:
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - "8080:80"
  pg-database:
    image: postgres:latest
    restart: on-failure
    container_name: pg-database
    env_file:
      - dev.env
    ports:
      - "5432:5432"
